config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"].freeze

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: CATEGORIES }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, numericality: {only_integer: true}
  validates :rating, inclusion: {in:0..5}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def new
    # We need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

 def index
    # recebe sinal de routes.rb dizendo que é pra invocar essa ação

    # define todas as variaveis necessarias
    @restaurants = Restaurant.all

    # renderizar index.html.erb
  end

  def show
    # @task = Task.find(1)
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    # GET request para ver o formulario
    # criando um Task novo SEM ATRIBUTOS para poder criar o formulario
    @restaurant = Restaurant.new
  end

  def create
    # POST para criar Task
    # criar um Task novo usando a info que veio do formulario
    @restaurant = Restaurant.new(new_restaurant_params)
    # guardar no banco de dados
    if @restaurant.save
      redirect_to restaurant_path(@restaurant.id)
    else
      render :new, status: :unprocessable_entity
    end

    # raise

    # redireccionar ao show page do Task que acabamos de criar
    # redirect_to task_path(@task.id)
    # redirect_to task_path(2)
  end

  def edit
    # @task = Task.find(2)
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    # achar o Task usando o ID nos parametros
    @restaurant = Restaurant.find(params[:id])
    # atualizar o Task usando a info que veio do formulario
    @restaurant.update(update_restaurant_params)

    # redireccionar ao show page do Task que acabamos de atualizar
    # redirect_to task_path(@task.id)
    # redirect_to task_path(2)
    redirect_to restaurant_path(@restaurant.id)
  end

  def destroy
    # achar o Task usando o ID nos parametros
    @restaurant = Restaurant.find(params[:id])
    # usar o metodo .destroy do ActiveRecord para deletar o Task do banco de dados
    @restaurant.destroy

    # redireccionar ao index page
    redirect_to restaurants_path, status: :see_other
  end

  private

  # params para criar um Task (apenas title + details)
  # não queremos deixar o usuario criar um Task com 'completed: true'
  def new_restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  # params para atualizar um Task (title, details + completed)
  def update_restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # GET request para ver o formulario
    # criando um Task novo SEM ATRIBUTOS para poder criar o formulario
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(new_review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # params para criar um Task (apenas title + details)
  # não queremos deixar o usuario criar um Task com 'completed: true'
  def new_review_params
    params.require(:review).permit(:rating, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<h2>Edit task</h2>

<%= form_with model: @restaurant do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>

    <%= f.label :category %>
    <%= f.text_field :category %>

    <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h2>RESTAURANTS</h2>

<ul>
    <% @restaurants.each do |restaurant| %>
        <li>
            <%#= link_to restaurant.title, restaurant_path(restaurant.id) %>
            <%= link_to restaurant.name, restaurant_path(restaurant) %>

            <%#= link_to "Laundry", "/restaurants/1" %>
        </li>
    <% end %>
</ul>

<%= link_to "Create restaurant", new_restaurant_path %>
<%#= link_to "Create restaurant", "/restaurants/new" %>


<%# link_to "text do link", url %>
<%#= link_to "Go to link", "https://www.google.com" %>


<%# fazer isso... %>
<%#= link_to "Go to index", restaurants_path %>
<%# ...é igual que fazer isso %>
<%#= link_to "Go to index", "/restaurants" %>

app/views/restaurants/new.html.erb
<!-- app/views/reviews/new.html.erb -->
<h1>New restaurant</h1>
<%= simple_form_for [@restaurant] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit "Submit restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurant name: <%= @restaurant.name %></h1>
<p>Restaurant category: <%= @restaurant.category %></p>


<p>
    <%#= link_to "Edit", "/restaurants/2/edit" %>
    <%#= link_to "Edit", edit_restaurant_path(@restaurant.id) %>
    <%= link_to "Edit", edit_restaurant_path(@restaurant) %>
</p>

<p>
    <%= link_to "Destroy",
        restaurant_path(@restaurant),
        data: {turbo_method: :delete,
               turbo_confirm: "Do you want to delete #{@restaurant.name}?"} %>
</p>

<p>
    <%= link_to "Go to index", restaurants_path %>
</p>

<p>
    <%= link_to "Make a review", new_restaurant_review_path(@restaurant) %>
</p>

app/views/reviews/new.html.erb
<!-- app/views/reviews/new.html.erb -->
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>